window.Game = {
  path: [],
  spawnDelayMultiplier: 1,
  spedUp: false,
  volume: 0.5,
  sfxVolume: 0.5,
  musicVolume: 0.5,
  isMuted: false,
  gold: 5,
  enemies: [],
  towers: [],
  castleHealth:20,
  selectedTower: null,
  selectedBuyButton: null,
  draggingTowerType: null,
  startLevel: false,
  autoStartLevel: false,
  assets: {
    logo: null,
    archerTower: null,
    castle: null,
    trash: null,
    twoxicon: null,
    volumeIcon: null,
    muteIcon: null,
	  background: null,
    startRoundButton: null,
    startRoundButtonHover: null,
    roundActiveButton: null,
    switchToManualButton: null,
    switchToManualButtonHover: null,
    switchToAutoButton: null,
    switchToAutoButtonHover: null,
	enemyHit: null,
  },
  ui: {
    towerButtons: [
      { type: 1, x: 1375, y: 150, w: 100, h: 100 },
      { type: 2, x: 1375, y: 270, w: 100, h: 100 },
      { type: 3, x: 1375, y: 390, w: 100, h: 100 },
    ],
    trashButton: { x: 1375, y: 600, w: 100, h: 100 },
    startRoundButton: { x: 1320, y: 740, w: 170, h: 38 }, // 170, 34 (original values, changed for image buttons)
    modeToggleButton: { x: 1320, y: 782, w: 170, h: 38 }, // 170, 34 (original values, changed for image buttons)
    settingIconButton: { x: 1495, y: 740, w: 34, h: 34 },
    speedUpButton:     { x: 1495, y: 785, w: 34, h: 34 },
    autoStartButton: null,
    startLevelButton: null,
  },
  level: null,
};
